version: '3.4'

services:
  next_app:
    container_name: mynextmuiauthapp_dev
    image: mynextmuiauthapp_dev:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: always
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: npm run dev
